#!/bin/bash
echo "=== FABRIC PARAMETER TEST ==="
echo ""
echo "1. Start the app"
echo "2. Make sure you have audio input (play some audio)"
echo "3. Move a knob (like Size) from 50% to 100%"
echo "4. Watch the console output"
echo ""
echo "You should see:"
echo "  - 'Parameter change request: size = [value]'"
echo "  - 'Normalized value: [0.0-1.0]'"
echo "  - '✅ Parameter set! Current raw: [0-100]'"
echo "  - 'DSP Parameters - Size: [value]' (every ~22ms)"
echo ""
echo "If you see parameter changes but no DSP changes,"
echo "the issue is that setValueNotifyingHost() isn't working."
echo ""
echo "Run: cd Builds/MacOSX && ./build/Debug/Fabric.app/Contents/MacOS/Fabric 2>&1 | grep -E 'Parameter|DSP Parameters'"
